CAMPAIGN_ADD = 'Campaign Added'
CAMPAIGN_DELETE = 'Campaign Deleted'
CAMPAIGN_DESCRIPTION = 'Campaign Description Updated'
CAMPAIGN_SESSION = 'Campaign Session Date Updated'
CAMPAIGN_ROLE = 'Campaign Role Updated'

ONESHOT_ADD = 'Oneshot Added'
ONESHOT_DELETE = 'Oneshot Deleted'
ONESHOT_DESCRIPTION = 'Oneshot Description Updated'
ONESHOT_CHANNEL = 'Oneshot Channel Updated'
ONESHOT_TIME = 'Oneshot Time Updated'
