CAMPAIGN_ADD = 'Added campaign "{}" with ID "{}" by user "{}"'
CAMPAIGN_DELETE = 'Deleted campaign "{}" with ID "{}"'
CAMPAIGN_DESCRIPTION = 'Updated description for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_SESSION = 'Updated session time for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_ROLE = 'Updated notification role for campaign "{}" with ID "{}" to "{}"'

ONESHOT_ADD = 'Oneshot Added'
ONESHOT_DELETE = 'Oneshot Deleted'
ONESHOT_DESCRIPTION = 'Oneshot Description Updated'
ONESHOT_CHANNEL = 'Oneshot Channel Updated'
ONESHOT_TIME = 'Oneshot Time Updated'
