CAMPAIGN_ADD = 'Added campaign "{}" with ID "{}" by user "{}"'
CAMPAIGN_DELETE = 'Deleted campaign "{}" with ID "{}"'
CAMPAIGN_DESCRIPTION = 'Updated description for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_SESSION = 'Updated session time for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_CHANNEL = 'Updated channel for notifications for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_ROLE = 'Updated notification role for campaign "{}" with ID "{}" to "{}"'
CAMPAIGN_EXTRA_NOTIFICATION = 'Updated extra notification state for campaign "{}" with ID "{}" to "{}"'

ONESHOT_ADD = 'Added oneshot "{}" with ID "{}" by user "{}"'
ONESHOT_DELETE = 'Deleted oneshot "{}" with ID "{}"'
ONESHOT_DESCRIPTION = 'Updated description for oneshot "{}" with ID "{}" to "{}"'
ONESHOT_CHANNEL = 'Updated channel for oneshot "{}" with ID "{}" to "{}"'
ONESHOT_TIME = 'Updated time for oneshot "{}" with ID "{}" to "{}"'
